Add One-to-Many Relationship with Definitions and Sentences
TheOpenDictionary/odict-web pull request #12
Opened 2022-09-17 22:37 UTC by maxdemaio

This PR will add a one-to-many relationship between definitions and sentences in the database. I think this can be updated with a `prisma migrate`. I think this should be the last change to the DB before we start on the docker-compose file.

2022-11-07 05:45 UTC, Nickersoft requested changes

2022-11-07 05:45 UTC, Nickersoft commented on prisma/schema.prisma
> +  Definition Definition @relation(fields: [definitionID], references: [id])
```suggestion
  definition Definition @relation(fields: [definitionID], references: [id])
```

2022-11-09 17:48 UTC, maxdemaio commented on prisma/schema.prisma
> +  Definition Definition @relation(fields: [definitionID], references: [id])
Will make this fix 👍

2022-11-13 18:49 UTC, Nickersoft approved these changes

2022-11-15 23:28 UTC, merged